import { db, error, json, requireAuth, router } from '@appdeploy/sdk';

type PlayerProfile = { user_id:string; name?:string; email?:string; rating:number; games:number; streak:number; updated_at:number };
async function list<T=Record<string,unknown>>(table:string,limit=50){const r=await db.list<T>(table,{limit});return r.items as Array<T&{id:string}>}
async function seed(table:string,records:Record<string,unknown>[]){const x=await list(table,20);if(!x.length)await db.add(table,records)}
async function profile(ctx:any){const x=await list<PlayerProfile>('player_profiles');const old=x.find(r=>r.user_id===ctx.user.userId);if(old)return old;const p:PlayerProfile={user_id:ctx.user.userId,name:ctx.user.name,email:ctx.user.email,rating:1284,games:0,streak:7,updated_at:Date.now()};const [id]=await db.add('player_profiles',[p]);if(!id)throw new Error('profile creation failed');return {...p,id}}
async function bootstrap(){await seed('clubs',[{name:'Nusantara Chess Club',region:'Jawa Timur',members:84,type:'Club'},{name:'Jakarta Chess Collective',region:'DKI Jakarta',members:126,type:'Community'},{name:'Sumatera Chess Academy',region:'Sumatera Utara',members:61,type:'Academy'}]);await seed('tournaments',[{name:'NUSACHESS Open Series 01',format:'Swiss',location:'Online',date:'12 Oct 2026',status:'Registration'},{name:'Nusantara Rapid Cup',format:'Rapid',location:'Surabaya',date:'24 Oct 2026',status:'Upcoming'},{name:'NUSACHESS League · Season 01',format:'Team',location:'Hybrid',date:'Nov 2026',status:'Planning'}]);await seed('fair_play_signals',[{player:'Sample review queue',signal:'Move-time anomaly',risk:'Medium',status:'Human review'}]);await seed('players_public',[{name:'NUSACHESS Player',rating:1284,club:'Nusantara Chess Club',status:'Active'},{name:'Development Candidate',rating:1512,club:'Jakarta Chess Collective',status:'Active'},{name:'Junior Player',rating:1198,club:'Sumatera Chess Academy',status:'Development'}])}
export const handler=router({
 'GET /api/_healthcheck':[async()=>json({ok:true,service:'nusachess-core',architecture:'mobile-web-management-core',version:'1.0'})],
 'GET /api/me':[requireAuth(),async ctx=>{const p=await profile(ctx);return json({profile:p,stats:{rating:p.rating,games:p.games,streak:p.streak}})}],
 'GET /api/ecosystem':[requireAuth(),async()=>{await bootstrap();const [clubs,tournaments,signals,players]=await Promise.all([list('clubs'),list('tournaments'),list('fair_play_signals'),list('players_public')]);return json({clubs,tournaments,signals,players,meta:{core:'NUSACHESS Core',realtime:true}})}],
 'POST /api/games':[requireAuth(),async ctx=>{const b=(ctx.body||{}) as {result?:string;from?:number[];to?:number[]};if(!b.result)return error('result is required',400);const [id]=await db.add('games',[{user_id:ctx.user.userId,result:b.result,from:b.from,to:b.to,created_at:Date.now()}]);if(!id)return error('game write failed',500);const p=await profile(ctx),next={...p,games:Number(p.games||0)+1,updated_at:Date.now()};const [ok]=await db.update('player_profiles',[{id:p.id,record:next}]);if(!ok)return error('profile update failed',500);return json({ok:true,game_id:id,stats:{rating:next.rating,games:next.games,streak:next.streak}})}],
 'POST /api/management/tournaments':[requireAuth(),async ctx=>{const b=(ctx.body||{}) as Record<string,unknown>;if(!b.name)return error('name is required',400);const [id]=await db.add('tournaments',[{name:b.name,format:b.format||'Swiss',location:b.location||'Online',date:b.date||'TBD',status:'Planning'}]);if(!id)return error('create failed',500);return json({id})}]
});