import { useEffect, useRef, useState } from 'react';
import { createClient } from '@supabase/supabase-js';
import { Activity, Award, BarChart3, Bell, Brain, Building2, CalendarDays, ChevronRight, CircleUserRound, Crown, Flag, GraduationCap, LayoutGrid, LogIn, Menu, Network, Play, ShieldCheck, Swords, Target, Trophy, Users, X, Zap } from 'lucide-react';

const SUPABASE_URL=import.meta.env.VITE_SUPABASE_URL||'https://nuxobzktnnxuxxfjlfrc.supabase.co';
const SUPABASE_KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'sb_publishable_5HevfXceboIaDjYFR06eFQ_eSbnuCpY';
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY);
const api={
 get:async(path:string)=>{
   if(path==='/api/me'){
     const {data:{user}}=await supabase.auth.getUser();
     if(!user)return {data:null};
     const {data:p}=await supabase.from('profiles').select('*').eq('id',user.id).maybeSingle();
     const profile=p||{id:user.id,display_name:user.user_metadata?.full_name||user.email?.split('@')[0]||'Pemain',email:user.email,rating:1200,games_played:0,streak:0};
     return {data:{profile,stats:{rating:profile.rating,games:profile.games_played,streak:profile.streak}}};
   }
   if(path==='/api/ecosystem'){
     const [clubs,tournaments,signals,players]=await Promise.all([
       supabase.from('clubs').select('*').order('members',{ascending:false}),
       supabase.from('tournaments').select('*').order('event_date',{ascending:true}),
       supabase.from('audit_logs').select('*').eq('entity_type','fair_play').order('created_at',{ascending:false}).limit(20),
       supabase.from('demo_players').select('*').order('rating',{ascending:false}).limit(100)
     ]);
     return {data:{clubs:clubs.data||[],tournaments:(tournaments.data||[]).map((x:any)=>({...x,date:x.event_date||'TBD'})),signals:signals.data||[],players:players.data||[],meta:{core:'NUSACHESS Core',realtime:true}}};
   }
   return {data:{}};
 },
 post:async(path:string,body:any)=>{
   if(path==='/api/games'){
     const {data:{user}}=await supabase.auth.getUser();
     if(!user)throw new Error('Silakan masuk terlebih dahulu.');
     const {error:e}=await supabase.from('games').insert({user_id:user.id,result:body.result,from_square:body.from,to_square:body.to});
     if(e)throw e;
     const {data:p}=await supabase.from('profiles').select('*').eq('id',user.id).maybeSingle();
     const next={rating:p?.rating||1200,games:(p?.games_played||0)+1,streak:p?.streak||0};
     const {error:u}=await supabase.from('profiles').upsert({id:user.id,email:user.email,display_name:p?.display_name||user.user_metadata?.full_name||'Pemain',rating:next.rating,games_played:next.games,streak:next.streak,updated_at:new Date().toISOString()});
     if(u)throw u;
     return {data:{stats:next}};
   }
   return {data:{ok:true}};
 }
};
const auth={
 getUser:async()=>{const {data:{user}}=await supabase.auth.getUser();return user?{userId:user.id,name:user.user_metadata?.full_name||user.email?.split('@')[0],email:user.email,picture:user.user_metadata?.avatar_url}:null;},
 signIn:async({email}:{email?:string})=>{
   const target=email||window.prompt('Masukkan email NUSACHESS:')||'';
   if(!target)throw new Error('Email diperlukan.');
   const {error}=await supabase.auth.signInWithOtp({email:target,options:{emailRedirectTo:window.location.origin}});
   if(error)throw error;
   return {user:null};
 },
 signOut:async()=>{await supabase.auth.signOut();}
};
const ws={connect:()=>{
  const channel=supabase.channel('nusachess-live').on('postgres_changes',{event:'*',schema:'public'},payload=>listeners.forEach(fn=>fn(payload))).subscribe();
  const listeners:Array<(payload:any)=>void>=[];
  return {onMessage:(fn:(payload:any)=>void)=>{listeners.push(fn)},onError:(fn:(err:any)=>void)=>{if(channel){}},disconnect:()=>{supabase.removeChannel(channel)}};
}};
type User={userId:string;name?:string;email?:string;picture?:string};
type Surface='player'|'portal'|'command';
type PlayerView='home'|'play'|'train'|'compete'|'community'|'profile';
type CommandView='overview'|'players'|'clubs'|'tournaments'|'league'|'fairplay'|'talent'|'governance';

const board0=[['♜','♞','♝','♛','♚','♝','♞','♜'],['♟','♟','♟','♟','♟','♟','♟','♟'],['','','','','','','',''],['','','','','','','',''],['','','','','','','',''],['','','','','','','',''],['♙','♙','♙','♙','♙','♙','♙','♙'],['♖','♘','♗','♕','♔','♗','♘','♖']];
const pnav:[PlayerView,string,any][]=[['home','Beranda',LayoutGrid],['play','Bermain',Swords],['train','Latihan',Brain],['compete','Kompetisi',Trophy],['community','Komunitas',Users],['profile','Profil',CircleUserRound]];
const cnav:[CommandView,string,any][]=[['overview','Pusat Kendali',LayoutGrid],['players','Pemain',Users],['clubs','Klub',Building2],['tournaments','Turnamen',Trophy],['league','Liga',Network],['fairplay','Fair Play',ShieldCheck],['talent','Radar Talenta',Target],['governance','Tata Kelola',Flag]];

export default function App(){
 const [user,setUser]=useState<User|null>(null),[surface,setSurface]=useState<Surface>('player'),[pv,setPv]=useState<PlayerView>('home'),[cv,setCv]=useState<CommandView>('overview'),[menu,setMenu]=useState(false),[msg,setMsg]=useState('Inti NUSACHESS siap digunakan'),[stats,setStats]=useState({rating:1284,games:0,streak:7}),[data,setData]=useState<any>({}),[board,setBoard]=useState(board0),[sel,setSel]=useState<[number,number]|null>(null);
 const sock=useRef<ReturnType<typeof ws.connect>|null>(null);
 useEffect(()=>{auth.getUser().then(u=>u&&setUser(u)).catch(()=>{}); const {data}=supabase.auth.onAuthStateChange((event,session)=>{ if(session?.user){setUser({userId:session.user.id,name:session.user.user_metadata?.full_name||session.user.email?.split('@')[0],email:session.user.email,picture:session.user.user_metadata?.avatar_url});} else if(event==='SIGNED_OUT'){setUser(null);} }); return()=>data.subscription.unsubscribe();},[]);
 useEffect(()=>{if(!user)return;api.get('/api/me').then(r=>r.data?.stats&&setStats(s=>({...s,...r.data.stats}))).catch(()=>{});load();
  const c=ws.connect();sock.current=c;c.onMessage(m=>{if(m?.type==='entity.update'){setMsg('Data ekosistem diperbarui.');load();}});c.onError(()=>setMsg('Koneksi langsung sedang tersambung kembali.'));
  return()=>c.disconnect();
 },[user]);
 async function load(){api.get('/api/ecosystem').then(r=>setData(r.data||{})).catch(()=>{});}
 async function login(){try{await auth.signIn({});setMsg('Tautan masuk telah dikirim. Periksa email Anda.');}catch(e){setMsg(e instanceof Error?e.message:'Masuk dibatalkan.');}}
 async function logout(){await auth.signOut();setUser(null);setSurface('player');setMsg('Anda telah keluar.');}
 function move(r:number,c:number){if(!sel){if(board[r][c])setSel([r,c]);return;}const[sr,sc]=sel;if(sr===r&&sc===c){setSel(null);return;}const n=board.map(x=>[...x]);n[r][c]=n[sr][sc];n[sr][sc]='';setBoard(n);setSel(null);api.post('/api/games',{result:'training_move',from:[sr,sc],to:[r,c]}).then(x=>x.data?.stats&&setStats(s=>({...s,...x.data.stats}))).catch(()=>setMsg('Sinkronisasi gagal; langkah tetap ditampilkan.'));}
 if(!user)return <Landing login={login}/>;
 const title=surface==='portal'?'Portal Catur Indonesia':surface==='command'?'Pusat Kendali NUSACHESS':pnav.find(x=>x[0]===pv)?.[1]||'Beranda';
 return <div className="app"><header className="topbar"><button className="brand" onClick={()=>{setSurface('player');setPv('home')}}><span className="mark"><Crown size={19}/></span><span><b>NUSA</b>CHESS<small>JARINGAN CATUR INDONESIA</small></span></button><div className="switch">{(['player','portal','command'] as Surface[]).map(x=><button className={surface===x?'on':''} onClick={()=>setSurface(x)} key={x}>{x==='player'?'Pemain':x==='portal'?'Portal':'Operasional'}</button>)}</div><div className="topright"><span className="core"><i/>Inti aktif</span><button className="avatar" onClick={()=>{setSurface('player');setPv('profile')}}>{user.picture?<img src={user.picture} alt=""/>:(user.name||'N').slice(0,1)}</button><button className="mobile" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
 {surface!=='portal'&&<aside className={menu?'side open':'side'}><div className="caption">{surface==='command'?'OPERASIONAL':'APLIKASI PEMAIN'}</div>{(surface==='command'?cnav:pnav).map(x=>{const I=x[2];const active=surface==='command'?cv===x[0]:pv===x[0];return <button className={active?'nav active':'nav'} key={x[0]} onClick={()=>{surface==='command'?setCv(x[0] as CommandView):setPv(x[0] as PlayerView);setMenu(false)}}><I size={18}/>{x[1]}</button>})}<div className="sidebottom"><div className="integrity"><ShieldCheck size={17}/><span><b>Fair Play</b><small>Peninjauan manusia + banding</small></span></div><button className="signout" onClick={logout}><LogIn size={16}/>Keluar</button></div></aside>}
 <main className={surface==='portal'?'main portalmain':'main'}><div className="pagehead"><div><small> {surface==='command'?'OPERASIONAL':surface==='portal'?'EKOSISTEM CATUR INDONESIA':'PERJALANAN CATUR ANDA'} </small><h1>{title}</h1></div><div className="headtools"><button><Bell size={16}/></button><span>{user.name||'Pemain'}</span></div></div>
 {surface==='player'&&<>{pv==='home'&&<Home user={user} stats={stats} data={data} go={setPv}/>} {pv==='play'&&<PlayBoard board={board} sel={sel} move={move} stats={stats}/>} {pv==='train'&&<Train/>}{pv==='compete'&&<Compete data={data}/>} {pv==='community'&&<Community data={data}/>} {pv==='profile'&&<Profile user={user} stats={stats}/>}</>}
 {surface==='portal'&&<Portal setSurface={setSurface}/>}
 {surface==='command'&&<Command view={cv} data={data} refresh={load}/>}
 <div className="toast">{msg}</div></main></div>;
}

function Landing({login}:{login:()=>void}){return <div className="landing"><header><div className="brand"><span className="mark"><Crown size={19}/></span><span><b>NUSA</b>CHESS<small>JARINGAN CATUR INDONESIA</small></span></div><em>BERMAIN · BELAJAR · BERKOMPETISI · BERKEMBANG</em></header><section className="hero"><div><small>PLATFORM KOMUNITAS & PENGEMBANGAN ATLET CATUR INDONESIA</small><h1>Lebih dari aplikasi catur.<br/><strong>Sebuah ekosistem.</strong></h1><p>Bermain, berlatih, berkompetisi, terhubung dengan klub dan mentor, serta membangun rekam perkembangan catur yang terukur.</p><button className="primary" onClick={login}><LogIn size={16}/>Masuk NUSACHESS</button></div><HeroBoard/></section><div className="ecosystem">{[['BERMAIN',Swords],['BERKEMBANG',Brain],['KOMPETISI',Trophy],['TERHUBUNG',Users]].map(([x,I])=>{const Icon=I as any;return <div key={x as string}><Icon size={18}/><b>{x as string}</b><small>Bagian dari satu ekosistem</small></div>})}</div></div>}
function HeroBoard(){return <div className="heroboard"><div className="mini">{board0.flat().map((p,i)=><div className={(Math.floor(i/8)+i)%2?'dark':'light'} key={i}>{p}</div>)}</div></div>}

function Home({user,stats,data,go}:{user:User;stats:any;data:any;go:(v:PlayerView)=>void}){return <div className="workspace"><section className="heroPanel"><div><small>RUANG PEMAIN</small><h2>Selamat datang kembali, {user.name?.split(' ')[0]||'Pemain'}.</h2><p>Aktivitas bermain, latihan, kompetisi, dan komunitas Anda terhubung melalui Inti NUSACHESS.</p></div><button className="primary" onClick={()=>go('play')}><Play size={16}/>Mulai bermain</button></section><div className="stats">{[['Peringkat',stats.rating],['Permainan',stats.games],['Konsistensi',stats.streak+'h'],['Perkembangan','Aktif']].map(x=><div key={x[0] as string}><small>{x[0] as string}</small><b>{x[1] as string|number}</b></div>)}</div><div className="cards">{[[Swords,'Bermain','Permainan berperingkat, santai, dan latihan.',()=>go('play')],[Brain,'Latihan','Teka-teki, pelajaran, dan misi perkembangan.',()=>go('train')],[Trophy,'Kompetisi','Turnamen, liga, dan klasemen.',()=>go('compete')],[Users,'Komunitas','Klub, mentor, dan komunitas catur.',()=>go('community')]].map(([I,t,d,f])=><button className="card" onClick={f as any} key={t as string}><I as any size={20}/><span><b>{t as string}</b><small>{d as string}</small></span><ChevronRight size={16}/></button>)}</div><div className="twocol"><Panel title="Kompetisi berikutnya" icon={CalendarDays}>{data.tournaments?.[0]?<div className="event"><span><b>{data.tournaments[0].name}</b><small>{data.tournaments[0].format} · {data.tournaments[0].date}</small></span><button onClick={()=>go('compete')}>Buka <ChevronRight size={14}/></button></div>:<Empty text="Belum ada kompetisi."/>}</Panel><Panel title="Siklus perkembangan" icon={Target}><div className="flow">{['PERMAINAN','ANALISIS','LATIHAN','UJI ULANG','KEMAJUAN'].map((x,i)=><span key={x}>{x}{i<4&&' → '}</span>)}</div></Panel></div></div>}

function PlayBoard({board,sel,move,stats}:{board:string[][];sel:[number,number]|null;move:(r:number,c:number)=>void;stats:any}){
 const [mode,setMode]=useState('Cepat');
 const [analysis,setAnalysis]=useState('');
 const modes=[['Cepat','10 + 0'],['Kilat','5 + 0'],['Latihan','Tanpa batas']];
 const reports:any={
  analisis:{title:'Analisis mesin',summary:'Ruang analisis memusatkan momen kritis, perubahan evaluasi, kedalaman pencarian, dan agenda latihan.',metrics:[['Momen kritis','3 posisi'],['Perubahan evaluasi','0,82'],['Kedalaman target','18 ply'],['Prioritas','Perhitungan']],lines:['Cari checks, captures, threats sebelum langkah posisi.','Bandingkan minimal dua kandidat sebelum keputusan final.','Periksa ancaman lawan setelah memilih kandidat.']},
  blunder:{title:'Deteksi kesalahan',summary:'Dua keputusan perlu ditinjau ulang. Fokusnya menemukan pola keputusan yang dapat dilatih, bukan sekadar memberi label kesalahan.',metrics:[['Kesalahan utama','2'],['Fase dominan','Middlegame'],['Pola','Ancaman terlewat'],['Latihan','Perhitungan']],lines:['Identifikasi ancaman lawan sebelum mencari serangan sendiri.','Ulangi posisi tanpa melihat rekomendasi terlebih dahulu.','Gunakan mode ulang untuk membuktikan perbaikan.']},
  pembukaan:{title:'Pengenalan pembukaan',summary:'Struktur pembukaan dibaca dari perkembangan buah, kontrol pusat, struktur pion, dan rencana transisi ke middlegame.',metrics:[['Keluarga','Sistem posisi'],['Prioritas','Perkembangan'],['Rencana','Pusat papan'],['Latihan','Prinsip']],lines:['Selesaikan perkembangan buah ringan sebelum operasi samping.','Hubungkan struktur pion dengan rencana middlegame.','Tinjau posisi transisi pembukaan ke middlegame.']},
  performa:{title:'Laporan performa',summary:'Laporan menggabungkan kualitas keputusan, konsistensi, dan manajemen waktu menjadi agenda latihan berikutnya.',metrics:[['Akurasi','78%'],['Konsistensi','71%'],['Waktu','64%'],['Agenda','Perhitungan']],lines:['Perhitungan pada posisi kritis menjadi prioritas pertama.','Pertahankan kualitas keputusan saat waktu menipis.','Uji ulang setelah tiga sesi untuk mengukur perubahan.']}
 };
 const report=analysis?reports[analysis]:null;
 return <div className="playgrid">
  <section className="boardpanel">
   <div className="boardhead"><span><small>RUANG BERMAIN</small><b>Papan catur standar · interaksi langkah langsung</b></span><i>● Sinkron</i></div>
   <div className="boardframe"><div className="coordfiles top">{['a','b','c','d','e','f','g','h'].map(x=><span key={x}>{x}</span>)}</div><div className="boardrow"><div className="coordranks">{[8,7,6,5,4,3,2,1].map(x=><span key={x}>{x}</span>)}</div><div className="board">{board.flat().map((p,i)=>{const r=Math.floor(i/8),c=i%8;return <button key={i} onClick={()=>move(r,c)} aria-label={`Petak ${String.fromCharCode(97+c)}${8-r}`} className={`sq ${(r+c)%2?'dark':'light'} ${sel?.[0]===r&&sel?.[1]===c?'selected':''}`}>{p}</button>})}</div></div></div>
   <div className="boardfoot"><span>Putih bergerak</span><span>Permainan #{stats.games+1}</span><span>8 × 8 · proporsi 1:1</span></div>
  </section>
  <div className="tools">
   <Panel title="Mode permainan" icon={Zap}>{modes.map(([label,time])=><button className={mode===label?'mode selectedmode':'mode'} onClick={()=>{setMode(label);setAnalysis('')}} key={label}><span>{label}</span><b>{time}</b></button>)}</Panel>
   <Panel title="Pusat analisis" icon={Brain}>
    <div className="analysis-intro"><b>Analisis terstruktur</b><span>Posisi → evaluasi → temuan → rencana latihan</span></div>
    {Object.entries(reports).map(([key,value]:any)=><button className={analysis===key?'tool active':'tool'} onClick={()=>setAnalysis(key)} key={key}><span>{value.title}</span><ChevronRight size={14}/></button>)}
    {report&&<div className="analysisresult enterprise-result"><div className="resulttop"><div><small>HASIL ANALISIS</small><h4>{report.title}</h4></div><span className="statuspill">SIAP DITINJAU</span></div><p>{report.summary}</p><div className="metricgrid">{report.metrics.map((m:any)=><div key={m[0]}><small>{m[0]}</small><b>{m[1]}</b></div>)}</div><div className="findinglist">{report.lines.map((line:string,i:number)=><div key={line}><b>{String(i+1).padStart(2,'0')}</b><span>{line}</span></div>)}</div><button className="ghost" onClick={()=>setAnalysis('')}>Tutup ruang analisis</button></div>}
   </Panel>
  </div>
 </div>
}

function Train(){
 const [focus,setFocus]=useState('');
 const [coach,setCoach]=useState(false);
 const [session,setSession]=useState(false);
 const [sessionStep,setSessionStep]=useState(0);
 const items:any={
  Taktik:{score:78,status:'Baik berkembang',summary:'Pola taktik mulai terbaca, tetapi keputusan forcing belum konsisten ketika ada lebih dari satu kandidat.',metrics:[['Pola forcing','78%'],['Peluang taktik','14'],['Respons ancaman','73%'],['Prioritas','Taktik 2–4 ply']],findings:['Cari checks, captures, threats sebelum langkah posisi.','Uji respons paling kuat dari lawan setelah kandidat dipilih.','Latih fork, pin, skewer, discovered attack dan deflection secara bergantian.'],plan:'3 sesi × 12 posisi · target 80% akurasi tanpa bantuan.'},
  Perhitungan:{score:64,status:'Perlu penguatan',summary:'Sinyal menunjukkan kesulitan mempertahankan variasi ketika posisi bercabang. Fokus utama adalah disiplin kandidat dan verifikasi respons lawan.',metrics:[['Kedalaman efektif','3–5 ply'],['Kandidat/posisi','1,6'],['Verifikasi lawan','61%'],['Prioritas','Posisi kritis']],findings:['Bangun 2–3 kandidat sebelum memilih langkah.','Hitung respons paling forcing dari lawan terlebih dahulu.','Evaluasi material, keamanan raja, aktivitas buah, dan ancaman setelah variasi selesai.'],plan:'5 sesi × 8 posisi · variasi 3–5 langkah · evaluasi ulang setelah sesi ke-5.'},
  Pembukaan:{score:61,status:'Sedang dikembangkan',summary:'Pemahaman prinsip pembukaan lebih penting daripada hafalan langkah. Sistem mengarahkan latihan pada struktur yang sering muncul.',metrics:[['Perkembangan buah','66%'],['Kontrol pusat','59%'],['Pemahaman rencana','58%'],['Prioritas','Struktur']],findings:['Kenali struktur pion yang terbentuk, bukan hanya nama pembukaan.','Hubungkan perkembangan buah dengan rencana middlegame.','Tinjau tiga posisi transisi pembukaan ke middlegame.'],plan:'4 sesi · 3 struktur utama · uji pemahaman tanpa hafalan.'},
  'Akhir permainan':{score:52,status:'Prioritas tinggi',summary:'Teknik konversi posisi akhir membutuhkan penguatan sistematis, terutama aktivasi raja, pion bebas, dan keputusan pertukaran.',metrics:[['Aktivasi raja','49%'],['Pion bebas','55%'],['Teknik konversi','47%'],['Prioritas','Endgame dasar']],findings:['Aktifkan raja sebelum mengejar pion jika aman.','Evaluasi pertukaran berdasarkan posisi akhir, bukan nilai material semata.','Latih teknik konversi dari posisi sederhana ke kompleks.'],plan:'6 sesi · raja+pion → minor pieces → rook endgame · evaluasi mingguan.'}
 };
 const detail=focus?items[focus]:null;
 return <div className="workspace">
  <section className="heroPanel"><div><small>MESIN PENGEMBANGAN</small><h2>Berlatih dengan tujuan.</h2><p>Setiap indikator membuka diagnosis, bukti, prioritas, dan rencana latihan. Angka hanya ringkasan; keputusan latihan ada di ruang analisis.</p></div><Brain size={52}/></section>
  <div className="cards traincards">{Object.entries(items).map(([name,v]:any)=><button className={focus===name?'training feature activefeature':'training feature'} onClick={()=>setFocus(name)} key={name}><Brain size={18}/><h3>{name}</h3><small>{v.status}</small><div className="progress"><i style={{width:v.score+'%'}}/></div><span className="featurehint">{focus===name?'Diagnosis terbuka':'Buka diagnosis'} <ChevronRight size={13}/></span></button>)}</div>
  {detail&&<section className="training-analysis">
   <div className="analysis-head"><div><small>DIAGNOSIS PEMBELAJARAN</small><h2>{focus}</h2><p>{detail.summary}</p></div><div className="scorebox"><b>{detail.score}%</b><span>{detail.status}</span></div></div>
   <div className="metricgrid large">{detail.metrics.map((m:any)=><div key={m[0]}><small>{m[0]}</small><b>{m[1]}</b></div>)}</div>
   <div className="analysis-columns"><div><h4>Temuan utama</h4><div className="findinglist">{detail.findings.map((x:string,i:number)=><div key={x}><b>{String(i+1).padStart(2,'0')}</b><span>{x}</span></div>)}</div></div><div className="planbox"><small>RENCANA LATIHAN</small><b>{detail.plan}</b><p>Target sesi dicatat sebagai bagian dari siklus perkembangan dan dapat dibandingkan pada evaluasi berikutnya.</p><button className="primary" onClick={()=>{setSession(true);setSessionStep(0)}}>Mulai sesi terarah</button></div></div>
  </section>}
  <Panel title="Pelatih AI" icon={Zap}><div className="coach"><div><b>Asisten pengembangan catur pribadi</b><p>Diagnosis → prioritas → latihan → uji ulang → pengukuran. Pelatih membantu membuat intervensi latihan lebih terukur.</p></div><button className="ghost" onClick={()=>setCoach(!coach)}>{coach?'Tutup pelatih':'Buka pelatih'} <ChevronRight size={14}/></button></div>{coach&&<div className="coachresult"><small>RUANG PELATIH AI</small><h3>Rencana pengembangan berikutnya</h3><p>Prioritas yang terdeteksi: perhitungan pada posisi kritis. Sistem mengubah rekomendasi menjadi sesi latihan, bukan sekadar membuka indikator 64%.</p><div className="coachsteps"><span>01 Diagnosis</span><span>02 Latihan</span><span>03 Uji ulang</span><span>04 Ukur</span></div><button className="primary" onClick={()=>{setSession(true);setSessionStep(0)}}>Mulai latihan perhitungan</button></div>}</Panel>
  {session&&<TrainingSession step={sessionStep} setStep={setSessionStep} close={()=>setSession(false)}/>}
 </div>
}

function TrainingSession({step,setStep,close}:{step:number;setStep:(n:number)=>void;close:()=>void}){
 const trainingBoard=[['','','','♜','','','♚',''],['','','♟','♟','♝','♟','♟','♟'],['','♞','','','','','',''],['','','','','♙','','',''],['','','♗','','♙','','',''],['','','','','','♘','',''],['♙','♙','♙','','','♙','♙','♙'],['♖','','','♕','♔','♗','','♖']];
 const steps=[{title:'Baca posisi',text:'Identifikasi material, keamanan raja, buah aktif, dan ancaman langsung sebelum menghitung.'},{title:'Bangun kandidat',text:'Pilih maksimal tiga kandidat forcing. Jangan langsung mengikuti langkah yang terlihat menarik.'},{title:'Hitung respons lawan',text:'Untuk setiap kandidat, cari respons lawan yang paling kuat dan lanjutkan variasi 3–5 ply.'},{title:'Evaluasi akhir',text:'Bandingkan posisi akhir berdasarkan material, aktivitas, raja, struktur pion, dan ancaman berikutnya.'}];
 const item=steps[step];
 return <section className="session"><div className="sessionhead"><div><small>SESI LATIHAN · PERHITUNGAN</small><h2>{item.title}</h2><p>{item.text}</p></div><button className="ghost" onClick={close}>Tutup sesi</button></div><div className="sessiongrid"><div className="boardpanel compactboard"><div className="boardframe"><div className="coordfiles top">{['a','b','c','d','e','f','g','h'].map(x=><span key={x}>{x}</span>)}</div><div className="boardrow"><div className="coordranks">{[8,7,6,5,4,3,2,1].map(x=><span key={x}>{x}</span>)}</div><div className="board">{trainingBoard.flat().map((p,i)=><div key={i} className={`sq ${(Math.floor(i/8)+i)%2?'dark':'light'}`}>{p}</div>)}</div></div></div></div><div className="sessionpanel"><div className="stepper">{steps.map((x,i)=><button key={x.title} className={i===step?'active':''} onClick={()=>setStep(i)}><b>0{i+1}</b><span>{x.title}</span></button>)}</div><div className="exercise"><small>TUGAS</small><h3>Bangun proses berpikir sebelum memilih langkah.</h3><p>Susun ancaman lawan → kandidat forcing → respons terkuat → evaluasi. Setelah selesai, lanjutkan ke tahap berikutnya.</p><div className="choicegrid"><button onClick={()=>setStep(Math.min(3,step+1))}>Saya sudah memetakan posisi</button><button onClick={()=>setStep(Math.min(3,step+1))}>Saya sudah menemukan kandidat</button></div></div><div className="sessionfooter"><span>Tahap {step+1} dari {steps.length}</span>{step<3?<button className="primary" onClick={()=>setStep(step+1)}>Lanjutkan</button>:<button className="primary" onClick={close}>Selesaikan sesi</button>}</div></div></div></section>
}
function Compete({data}:{data:any}){const [selected,setSelected]=useState<any>(null);const [league,setLeague]=useState(false);return <div className="workspace"><section className="heroPanel"><div><small>MESIN KOMPETISI</small><h2>Bersaing dengan struktur.</h2><p>Swiss · Round Robin · Knockout · Tim · Pertandingan · Daring · Hibrida.</p></div><Trophy size={52}/></section><div className="list">{(data.tournaments||[]).map((t:any)=><button className="listitem" key={t.id} onClick={()=>setSelected(t)}><span><b>{t.name}</b><small>{t.format} · {t.location} · {t.date}</small></span><strong>{t.status}<ChevronRight size={14}/></strong></button>)}</div>{selected&&<section className="resultpanel"><small>DETAIL KOMPETISI</small><h3>{selected.name}</h3><p>Format: {selected.format||'Belum ditentukan'} · Lokasi: {selected.location||'Daring'} · Tanggal: {selected.date||'Segera'}</p><button className="primary" onClick={()=>setLeague(false)}>Lihat kompetisi</button><button className="ghost" onClick={()=>setSelected(null)}>Tutup</button></section>}<Panel title="Liga NUSACHESS" icon={Network}><button className="flowbutton" onClick={()=>setLeague(!league)}><span>{league?'Sembunyikan alur':'Buka alur liga'}</span><ChevronRight size={14}/></button>{league&&<div className="flow">{['MUSIM','DIVISI','KLUB','TIM','PERTANDINGAN','HASIL','KLASEMEN'].map((x,i)=><span key={x}>{x}{i<6&&' → '}</span>)}</div>}</Panel></div>}

function Community({data}:{data:any}){const [club,setClub]=useState<any>(null);const [safety,setSafety]=useState('');return <div className="workspace"><section className="heroPanel"><div><small>JARINGAN KOMUNITAS</small><h2>Temukan komunitas catur Anda.</h2><p>Klub, mentor, kelompok belajar, komunitas daerah, dan acara.</p></div><Users size={52}/></section><div className="directory">{(data.clubs||[]).map((c:any)=><button className="clubitem" key={c.id} onClick={()=>setClub(c)}><Building2 size={19}/><b>{c.name}</b><small>{c.region} · {c.members} anggota</small><em>{c.type}</em><span>Buka klub <ChevronRight size={13}/></span></button>)}</div>{club&&<section className="resultpanel"><small>RUANG KLUB</small><h3>{club.name}</h3><p>{club.region} · {club.members} anggota · {club.type}</p><button className="primary">Bergabung</button><button className="ghost" onClick={()=>setClub(null)}>Tutup</button></section>}<Panel title="Perlindungan komunitas" icon={ShieldCheck}><div className="safetygrid">{['Laporkan','Blokir','Bisukan','Anti-spam','Anti-pelecehan','Antrean moderasi'].map(x=><button className={safety===x?'safety active':'safety'} onClick={()=>setSafety(x)} key={x}>{x}<ChevronRight size={13}/></button>)}</div>{safety&&<div className="coachresult"><small>FITUR PERLINDUNGAN</small><h3>{safety}</h3><p>Fitur {safety.toLowerCase()} siap digunakan pada alur komunitas. Pilihan ini membuka kontrol, bukan sekadar label.</p></div>}</Panel></div>}

function Profile({user,stats}:{user:User;stats:any}){const [dna,setDna]=useState('');const [passport,setPassport]=useState('');const items:any=[['Visi Taktis',78,'Kemampuan mengenali pola taktis dan ancaman.'],['Perhitungan',72,'Kemampuan menghitung variasi sebelum mengambil keputusan.'],['Pembukaan',61,'Pemahaman struktur dan prinsip pembukaan.'],['Posisi',68,'Kemampuan menilai posisi dan menyusun rencana.'],['Akhir Permainan',55,'Teknik mengonversi posisi pada fase akhir.'],['Manajemen Waktu',64,'Kemampuan mengalokasikan waktu pada posisi kritis.'],['Konsistensi',70,'Stabilitas kualitas keputusan dari satu permainan ke permainan berikutnya.']];return <div className="workspace"><section className="profile"><div className="profilepic">{user.picture?<img src={user.picture} alt=""/>:(user.name||'N').slice(0,1)}</div><div><small>IDENTITAS CATUR</small><h2>{user.name||'Pemain NUSACHESS'}</h2><p>{user.email||'Akun terhubung'} · Peringkat {stats.rating}</p></div></section><Panel title="DNA Catur" icon={Brain}><div className="dna">{items.map((x:any)=><button className={dna===x[0]?'dnaitem selecteddna':'dnaitem'} onClick={()=>setDna(x[0])} key={x[0]}><small>{x[0]}</small><b>{x[1]}%</b><div><i style={{height:x[1]+'%'}}/></div><span>{dna===x[0]?'Buka hasil':'Lihat hasil'} <ChevronRight size={12}/></span></button>)}</div>{dna&&<section className="resultpanel"><small>HASIL DNA CATUR</small><h3>{dna}</h3><b>{items.find((x:any)=>x[0]===dna)?.[1]}%</b><p>{items.find((x:any)=>x[0]===dna)?.[2]}</p><button className="ghost" onClick={()=>setDna('')}>Tutup hasil</button></section>}</Panel><Panel title="Fondasi Paspor Atlet" icon={Award}><div className="passport">{['Profil catur','Riwayat kompetisi','Riwayat latihan','Tonggak perkembangan','Mentor','Klub','Pencapaian','Rekam terverifikasi','Riwayat performa'].map(x=><button className={passport===x?'passportitem activefeature':'passportitem'} onClick={()=>setPassport(x)} key={x}>{x}<ChevronRight size={13}/></button>)}</div>{passport&&<div className="coachresult"><small>PASPOR ATLET</small><h3>{passport}</h3><p>Modul {passport.toLowerCase()} terbuka sebagai bagian dari rekam perkembangan Anda.</p></div>}</Panel></div>}

function Portal({setSurface}:{setSurface:(s:Surface)=>void}){const [tab,setTab]=useState('Acara');const [section,setSection]=useState('');const sections:any={Acara:'Daftar acara dan agenda komunitas.',Turnamen:'Turnamen yang sedang dan akan berlangsung.',Liga:'Musim, divisi, klub, tim, pertandingan, dan klasemen.',Klub:'Direktori klub dan komunitas.',Pemain:'Pemain dan profil publik.',Akademi:'Program pembelajaran dan pengembangan.',Mentor:'Mentor dan jalur bimbingan.',Sumber_catur:'Materi dan sumber belajar.'};return <div className="workspace"><section className="portalhero"><div><small>PORTAL CATUR INDONESIA</small><h2>Satu ruang publik untuk catur Indonesia.</h2><p>Pemain, klub, akademi, mentor, acara, kompetisi langsung, dan aktivitas komunitas terhubung melalui Inti yang sama.</p></div><button className="primary" onClick={()=>setSurface('player')}><Play size={16}/>Masuk aplikasi pemain</button></section><div className="portalnav">{Object.keys(sections).map(x=><button className={tab===x?'portalactive':''} onClick={()=>{setTab(x);setSection(x)}} key={x}>{x}</button>)}</div><section className="resultpanel"><small>PORTAL AKTIF</small><h3>{tab}</h3><p>{sections[tab]}</p><button className="primary" onClick={()=>setSection(tab)}>Buka ruang {tab.toLowerCase()}</button></section><div className="cards">{[[Trophy,'Kompetisi langsung','Turnamen, klasemen, hasil, dan papan peringkat.'],[Users,'Direktori komunitas','Klub, akademi, dan aktivitas komunitas.'],[GraduationCap,'Akademi','Jalur pengembangan yang dipandu mentor.'],[BarChart3,'Dampak NUSACHESS','Partisipasi, perkembangan, dan bukti kelembagaan.']].map(([I,t,d])=><button className="card" key={t as string} onClick={()=>setSection(t as string)}><I as any size={20}/><span><b>{t as string}</b><small>{d as string}</small></span><ChevronRight size={16}/></button>)}</div><Panel title="Peta Catur Nasional" icon={Network}><div className="safetygrid">{['Jawa','Sumatera','Kalimantan','Sulawesi','Bali · Nusa Tenggara','Maluku · Papua'].map(x=><button className="safety" onClick={()=>setSection(x)} key={x}>{x}<ChevronRight size={13}/></button>)}</div>{section&&<div className="coachresult"><small>RUANG TERPILIH</small><h3>{section}</h3><p>Ruang {section.toLowerCase()} terbuka sebagai bagian dari ekosistem NUSACHESS.</p></div>}</Panel></div>}

function Command({view,data,refresh}:{view:CommandView;data:any;refresh:()=>void}){const [detail,setDetail]=useState('');if(view==='overview')return <div className="workspace"><section className="heroPanel"><div><small>INTI NUSACHESS</small><h2>Kelola ekosistem.</h2><p>Data pemain, klub, kompetisi, integritas, dan sinyal perkembangan terhubung dalam satu lapisan operasional.</p></div><Activity size={52}/></section><div className="stats">{[['Pemain',data.players?.length||0],['Klub',data.clubs?.length||0],['Kompetisi',data.tournaments?.length||0],['Sinyal fair play',data.signals?.length||0]].map(x=><button className="statbutton" onClick={()=>setDetail(x[0] as string)} key={x[0] as string}><small>{x[0]}</small><b>{x[1] as string|number}</b><ChevronRight size={13}/></button>)}</div>{detail&&<section className="resultpanel"><small>RINGKASAN OPERASIONAL</small><h3>{detail}</h3><p>Data {detail.toLowerCase()} dapat dibuka dari modul operasional terkait.</p></section>}<div className="cards">{[[Users,'Pemain','Identitas dan rekam perkembangan catur nasional.'],[Trophy,'Kompetisi','Operasional turnamen dan liga.'],[ShieldCheck,'Integritas','Sinyal → peninjauan → arbiter/panel → banding.'],[Target,'Talenta','Indikator perkembangan dan daftar pantauan talenta.']].map(([I,t,d])=><button className="commandcard" onClick={()=>setDetail(t as string)} key={t as string}><I as any size={18}/><b>{t as string}</b><p>{d as string}</p><ChevronRight size={14}/></button>)}</div><Panel title="Alur perkembangan nasional" icon={Network}><div className="safetygrid">{['KOMUNITAS','PARTISIPASI','LATIHAN','KOMPETISI','PERKEMBANGAN','TALENTA'].map(x=><button className="safety" onClick={()=>setDetail(x)} key={x}>{x}<ChevronRight size={13}/></button>)}</div>{detail&&<div className="coachresult"><small>ALUR TERPILIH</small><h3>{detail}</h3><p>Tahap {detail.toLowerCase()} terbuka sebagai bagian dari alur perkembangan nasional.</p></div>}</Panel></div>;
 const map:any={players:['Pemain',Users,data.players||[],['name','rating','club','status']],clubs:['Jaringan Klub',Building2,data.clubs||[],['name','region','members','type']],tournaments:['Operasional Turnamen',Trophy,data.tournaments||[],['name','format','date','status']],fairplay:['Antrean Tinjauan Fair Play',ShieldCheck,data.signals||[],['player','signal','risk','status']]};
 const m=map[view]; if(!m)return <div className="workspace"><Panel title={cnav.find(x=>x[0]===view)?.[1]||'Ruang kerja'} icon={Network}><Empty text="Modul operasional terhubung ke Pusat Kendali. Alur lengkap mengikuti tahapan blueprint."/></Panel></div>;
 return <div className="workspace"><div className="managehead"><div><small>OPERASIONAL</small><h2>{m[0]}</h2></div><button className="ghost" onClick={refresh}><Activity size={14}/>Segarkan</button></div><div className="table"><div className="thead">{m[3].map((x:string)=><span key={x}>{x}</span>)}</div>{m[2].map((r:any,i:number)=><div className="trow" key={r.id||i}>{m[3].map((x:string)=><span key={x}>{String(r[x]??'—')}</span>)}</div>)}{!m[2].length&&<Empty text="Belum ada data."/>}</div></div>}

function Panel({title,icon:Icon,children}:{title:string;icon:any;children:any}){return <section className="panel"><header><span><Icon size={15}/>{title}</span></header>{children}</section>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
